s = set()
# for i in range (8):
#     s.add(input("enter your number: "))
s.add(18)
s.add(input("enter your number: "))
s.add(input("enter your number: "))
s.add(input("enter your number: "))
s.add(input("enter your number: "))
s.add(input("enter your number: "))
s.add(input("enter your number: "))
s.add(input("enter your number: "))
s.add(input("enter your number: "))
print(s)